version: '3.9'

services:
  db:
    build:
      context: ./db
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: clinicadb
      MYSQL_DATABASE: clinica
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pclinicadb"]
      interval: 10s
      timeout: 5s
      retries: 5

  usuarios:
    build:
      context: ./usuarios
    container_name: usuarios-container
    environment:
      MYSQL_ROOT_PASSWORD: usuariosdb
      MYSQL_DATABASE: usuarios
    ports:
      - "3307:3306"
    volumes:
      - db_usuarios_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pusuariosdb"]
      interval: 10s
      timeout: 5s
      retries: 5


  php:
    build:
      context: ./php
    container_name: php-container
    volumes:
      - ./php:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      node:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - backend
      - frontend

  node:
    build:
      context: ./node
    container_name: node-container
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
  
  login:
    build: 
      context: ./login
    container_name: login-container
    ports:
      - "3002:3002"
    depends_on:
      usuarios:
        condition: service_healthy
    networks:
      - backend

volumes:
  db_data:
  db_usuarios_data:

networks:
  backend:
  frontend:
